### ISSUE TITLE
Uncaught TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by poga** [geksilla/atom-fuzzy-grep#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-fuzzy-grep](https://github.com/geksilla/atom-fuzzy-grep) package, v0.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'startsWith' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:745

TypeError: Cannot read property 'startsWith' of undefined
  at /Users/poga/.atom/packages/atom-fuzzy-grep/lib/runner.coffee:63:18
  at Array.some (native)
  at Runner.module.exports.Runner.isGitRepo (/Users/poga/.atom/packages/atom-fuzzy-grep/lib/runner.coffee:62:33)
  at Runner.module.exports.Runner.run (/Users/poga/.atom/packages/atom-fuzzy-grep/lib/runner.coffee:18:27)
  at GrepView.module.exports.GrepView.grepProject (/Users/poga/.atom/packages/atom-fuzzy-grep/lib/atom-fuzzy-grep-view.coffee:69:13)
  at /Users/poga/.atom/packages/atom-fuzzy-grep/lib/atom-fuzzy-grep-view.coffee:15:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:534:12)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:452:43)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:742:31
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:787:29
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1148:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:781:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1978:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1948:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:779:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:739:21)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:440:35)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```
### Commands

```
     -3:31.9.0 settings-view:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -3:28.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:44.7.0 core:close (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -1:42.6.0 pane:reopen-closed-item (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -1:41.6.0 core:close (div.settings-view.pane-item)
     -1:38.3.0 symbols-view:return-from-declaration (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:35.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:27.1.0 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:24.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:24.6.0 atom-terminal:open-project-root (atom-text-editor.editor.vim-mode.command-mode)
     -1:17.6.0 settings-view:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:47.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.3.0 pane:show-item-2 (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -0:07.4.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -0:05.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.3.0 fuzzy-grep:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "projectHome": "/Users/poga/projects",
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "symbols-tree-view"
    ]
  },
  "atom-fuzzy-grep": {}
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.0.0
atom-alignment, v0.12.1
atom-fuzzy-grep, v0.3.0
autocomplete-paths, v1.0.2
color-picker, v2.0.4
file-icons, v1.5.7
go-plus, v3.3.11
highlight-line, v0.11.0
language-haskell, v1.1.2
language-jade, v0.4.0
language-javascript-better, v1.5.0
language-livescript-edge, v1.0.0
language-rust, v0.4.3
last-cursor-position, v0.9.0
linter, v0.12.7
linter-rust, v0.1.0
racer, v0.13.0
react, v0.12.0
vim-mode, v0.53.0

# Dev
No dev packages
```

**Comment by geksilla** [comment]
@poga thanks for report.
