### ISSUE TITLE
Uncaught TypeError: Cannot read property 'startsWith' of null

### ISSUE THREAD

**Issue by Jack-Reason** [geksilla/atom-fuzzy-grep#12]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-fuzzy-grep](https://github.com/geksilla/atom-fuzzy-grep) package, v0.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'startsWith' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:745

TypeError: Cannot read property 'startsWith' of null
  at /Users/jrbp/.atom/packages/atom-fuzzy-grep/lib/runner.coffee:63:18
  at Array.some (native)
  at Runner.module.exports.Runner.isGitRepo (/Users/jrbp/.atom/packages/atom-fuzzy-grep/lib/runner.coffee:62:33)
  at Runner.module.exports.Runner.run (/Users/jrbp/.atom/packages/atom-fuzzy-grep/lib/runner.coffee:18:27)
  at GrepView.module.exports.GrepView.grepProject (/Users/jrbp/.atom/packages/atom-fuzzy-grep/lib/atom-fuzzy-grep-view.coffee:69:13)
  at /Users/jrbp/.atom/packages/atom-fuzzy-grep/lib/atom-fuzzy-grep-view.coffee:15:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:534:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:518:26
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:516:21)
  at TextBuffer.module.exports.TextBuffer.setText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:453:19)
  at TextEditor.module.exports.TextEditor.setText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:711:26)
  at TextEditorView.module.exports.TextEditorView.setText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/text-editor-view.js:52:25)
  at GrepView.module.exports.GrepView.setSelection (/Users/jrbp/.atom/packages/atom-fuzzy-grep/lib/atom-fuzzy-grep-view.coffee:85:25)
  at GrepView.module.exports.GrepView.toggle (/Users/jrbp/.atom/packages/atom-fuzzy-grep/lib/atom-fuzzy-grep-view.coffee:97:8)
  at atom-workspace.editorSubscription.atom.commands.add.fuzzy-grep:toggle (/Users/jrbp/.atom/packages/atom-fuzzy-grep/lib/atom-fuzzy-grep.coffee:22:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
 27x -6:52.3.0 core:select-right (atom-text-editor.editor.is-focused)
     -6:48.2.0 core:copy (atom-text-editor.editor.is-focused)
     -6:47.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -6:46.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:36 settings-view:open (atom-text-editor.editor.is-focused)
     -6:20.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:40.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.0 fuzzy-grep:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-fuzzy-grep, v0.3.0
chester-atom-syntax, v0.1.1
f5-networks-iRules, v0.1.0
language-cisco, v1.2.0
minimap, v4.10.1
minimap-find-and-replace, v4.2.0

# Dev
No dev packages
```

**Comment by geksilla** [comment]
@Jack-Reason, thanks for report. I think you catch this error when atom opened without any project and _Untitled_ buffer.
