### ISSUE TITLE
Uncaught Error: spawn EACCES using AG in an Elixir Phoenix project

### ISSUE THREAD

**Issue by npassaro** [geksilla/atom-fuzzy-grep#22]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-fuzzy-grep](https://github.com/geksilla/atom-fuzzy-grep) package, v0.7.0
### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
    at exports._errnoException (util.js:814:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:343:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at Runner.module.exports.Runner.run (/Users/npassaro/.atom/packages/atom-fuzzy-grep/lib/runner.coffee:35:22)
    at GrepView.module.exports.GrepView.grepProject (/Users/npassaro/.atom/packages/atom-fuzzy-grep/lib/atom-fuzzy-grep-view.coffee:90:13)
    at /Users/npassaro/.atom/packages/atom-fuzzy-grep/lib/atom-fuzzy-grep-view.coffee:23:10
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:645:20)
```
### Commands

```
     -0:13.4.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:08.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:08.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:07.3.0 fuzzy-grep:toggle (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "themes": [
      "nucleus-dark-ui",
      "batman-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "atom-fuzzy-grep": {
    "grepCommandString": "/usr/local/opt/the_silver_searcher\n"
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v4.4.0
atom-fuzzy-grep, v0.7.0
atomatigit, v1.5.5
autocomplete-elixir, v1.4.2
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
autocomplete-sass, v0.1.0
batman-syntax, v1.0.1
change-case, v0.6.0
color-picker, v2.0.13
ever-notedown, v0.2.11
highlight-selected, v0.10.1
html2haml, v0.10.0
language-diff, v0.3.1
language-elixir, v0.5.2
language-haml, v0.23.4
language-scala, v1.1.4
linter-haml, v1.0.0
minimap, v4.16.0
nucleus-dark-ui, v0.6.6
pigments, v0.18.1
ruby-block, v0.3.5

# Dev
No dev packages
```

**Comment by geksilla** [comment]
Hi @npassaro, it's look like file permissions issue. Is this reproducible on `git grep` and `ag`?

**Comment by npassaro** [comment]
Hi @geksilla, I think it was a problem with another package. Forgot completely that I had opened this issue. Sorry, I'll close it. Thank you!
